#!/usr/bin/env python3
"""Summarise audio duration for Common Voice wav.scp files.

The script matches utterances listed in a wav.scp file with the
`clip_durations.tsv` metadata shipped with Common Voice and prints
aggregate duration statistics.  It understands both direct file
references and the typical `ffmpeg -i <path> ... - |` command lines
generated by `local/data_prep.pl`.
"""

from __future__ import annotations

import argparse
import csv
import shlex
from pathlib import Path
from typing import Dict, Iterable, Tuple


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Summarise total duration from wav.scp and clip_durations.tsv"
    )
    parser.add_argument(
        "--wav-scp",
        type=Path,
        required=True,
        help="Path to wav.scp produced by ESPnet data preparation",
    )
    parser.add_argument(
        "--clip-durations",
        type=Path,
        required=True,
        help="Path to Common Voice clip_durations.tsv",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress per-utterance warnings for missing durations",
    )
    return parser.parse_args()


def load_durations(path: Path) -> Dict[str, int]:
    with path.open(encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        return {row["clip"]: int(row["duration[ms]"]) for row in reader}


def iter_audio_tokens(wav_scp_lines: Iterable[str]) -> Iterable[Tuple[str, str]]:
    for line in wav_scp_lines:
        line = line.strip()
        if not line:
            continue
        try:
            utt_id, command = line.split(maxsplit=1)
        except ValueError:
            continue
        tokens = shlex.split(command)
        audio_path = None
        if "-i" in tokens:
            idx = tokens.index("-i")
            if idx + 1 < len(tokens):
                audio_path = tokens[idx + 1]
        if audio_path is None and tokens:
            audio_path = tokens[0]
        if audio_path is None:
            continue
        yield utt_id, audio_path


def normalise_clip_name(path_str: str) -> str:
    name = Path(path_str).name
    if name.endswith(".wav"):
        return name.rsplit(".wav", 1)[0] + ".mp3"
    return name


def main() -> None:
    args = parse_args()
    durations = load_durations(args.clip_durations)
    total_ms = 0
    seen = 0
    missing = []

    with args.wav_scp.open(encoding="utf-8") as f:
        for utt_id, audio_path in iter_audio_tokens(f):
            clip_name = normalise_clip_name(audio_path)
            seen += 1
            value = durations.get(clip_name)
            if value is None:
                missing.append((utt_id, audio_path))
                continue
            total_ms += value

    total_seconds = total_ms / 1000
    total_hours = total_seconds / 3600
    total_days = total_hours / 24

    print(f"Utterances processed: {seen}")
    print(f"Matched clips:       {seen - len(missing)}")
    print(f"Missing clips:       {len(missing)}")
    print(f"Total milliseconds:  {total_ms}")
    print(f"Total seconds:       {total_seconds:.3f}")
    print(f"Total hours:         {total_hours:.3f}")
    print(f"Total days:          {total_days:.3f}")

    if missing and not args.quiet:
        print("\nMissing examples (utterance id :: audio path):")
        for utt_id, audio_path in missing[:20]:
            print(f"  {utt_id} :: {audio_path}")
        if len(missing) > 20:
            print(f"  ... {len(missing) - 20} more")


if __name__ == "__main__":
    main()
